include("${CMAKE_CURRENT_LIST_DIR}/dependencies/rapidfuzz.cmake")
if (EMSCRIPTEN)
else()
    include("${CMAKE_CURRENT_LIST_DIR}/dependencies/efsw.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/dependencies/spdlog.cmake")
endif()